name: Grace That Taught My Heart To Fear
favicon: null
layout_spectrum: 0.2298
typography_spectrum: 0.14579688711091876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cdcec0'
    - '#7a7f82'
    - '#b3b4ae'
    - '#545b65'
    - '#363749'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
