name: Grace That Taught My Heart To Fear
favicon: null
layout_spectrum: 0.09828188619576395
typography_spectrum: 0.14579688711091876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9104931531473994
  lightness: 0.4599244361743331
  saturation: 0.28360929689370096
  rhythmicContrast: 0.3483697953633964
purpose: []
